import React, { useState } from 'react';
import { EvaluationResult } from '../types';
import CriteriaChart from './CriteriaChart';
import { AlertTriangle, ThumbsDown, Check, TrendingUp, Cpu, Heart, ExternalLink, Link2, Loader2, Sparkles, X, Save, Mail } from 'lucide-react';
import { formalizeRefinementRule } from "../services/refinementService";

interface Props {
  evaluation: EvaluationResult;
  onRefine: (msg: string) => void;
  onCompare?: () => void;
  mandateName?: string;
}

const EvaluationCard: React.FC<Props> = ({ evaluation, onRefine, onCompare, mandateName }) => {
  const [showRefine, setShowRefine] = useState(false);
  const [refineText, setRefineText] = useState("");
  const [refineStatus, setRefineStatus] = useState<'idle' | 'processing' | 'review'>('idle');
  const [formalizedRule, setFormalizedRule] = useState("");

  const getScoreColor = (score: number) => {
    if (score >= 4) return 'text-emerald-400';
    if (score >= 3) return 'text-amber-400';
    return 'text-rose-400';
  };

  const ScoreRow = ({ label, score, reasoning, icon: Icon }: any) => (
    <div className="mb-4">
      <div className="flex justify-between items-center mb-1">
        <div className="flex items-center gap-2 text-slate-300">
          <Icon className="w-4 h-4" />
          <span className="font-medium text-sm uppercase tracking-wide">{label}</span>
        </div>
        <span className={`font-bold ${getScoreColor(score)}`}>{score}/5</span>
      </div>
      <p className="text-slate-400 text-xs leading-relaxed">{reasoning}</p>
    </div>
  );

  const handleRefineSubmit = async () => {
    if (!refineText.trim()) return;
    setRefineStatus('processing');
    try {
      const rule = await formalizeRefinementRule(refineText);
      setFormalizedRule(rule);
      setRefineStatus('review');
    } catch (e) {
      console.error(e);
      setFormalizedRule(refineText); // Fallback
      setRefineStatus('review');
    }
  };

  const handleConfirmRefine = () => {
    onRefine(formalizedRule);
    setShowRefine(false);
    setRefineText("");
    setFormalizedRule("");
    setRefineStatus('idle');
  };

  const handleCancelRefine = () => {
    setShowRefine(false);
    setRefineText("");
    setFormalizedRule("");
    setRefineStatus('idle');
  };

  const handleEmailExport = () => {
    const subject = `InnoScout Analysis: ${evaluation.startupName}`;
    const body = `
Startup Evaluation Report
-------------------------
Startup: ${evaluation.startupName}
Summary: ${evaluation.oneLineSummary}
Overall Score: ${evaluation.overallScore}/5
Result: ${evaluation.isNoGo ? 'NO-GO ⛔' : 'PROCEED ✅'}

--- DETAILED SCORING ---

1. Desirability (${evaluation.desirability.score}/5)
${evaluation.desirability.reasoning}

2. Viability (${evaluation.viability.score}/5)
${evaluation.viability.reasoning}

3. Feasibility (${evaluation.feasibility.score}/5)
${evaluation.feasibility.reasoning}

--- RED FLAGS ---
${evaluation.redFlags.length > 0 ? evaluation.redFlags.map(f => `- ${f}`).join('\n') : 'None detected.'}

--- SOURCES ---
${evaluation.sources && evaluation.sources.length > 0 ? evaluation.sources.join('\n') : 'N/A'}

Generated by InnoScout
`.trim();

    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className={`rounded-xl border ${evaluation.isNoGo ? 'border-rose-900 bg-rose-950/10' : 'border-slate-700 bg-slate-800'} overflow-hidden flex flex-col transition-all hover:shadow-2xl hover:border-slate-600`}>
      <div className="p-6 pb-4">
        <div className="flex justify-between items-start mb-2">
            <h3 className="text-xl font-bold text-white tracking-tight">{evaluation.startupName}</h3>
            
            <div className="flex items-center gap-2">
                {evaluation.isNoGo && (
                    <div className="flex items-center gap-1 bg-rose-900/50 text-rose-300 px-2 py-1 rounded text-xs font-bold uppercase border border-rose-700">
                        <ThumbsDown className="w-3 h-3" /> No-Go
                    </div>
                )}
                {!evaluation.isNoGo && evaluation.overallScore >= 4 && (
                     <div className="flex items-center gap-1 bg-emerald-900/50 text-emerald-300 px-2 py-1 rounded text-xs font-bold uppercase border border-emerald-700">
                     <Check className="w-3 h-3" /> Top Pick
                 </div>
                )}

                <div className="w-px h-4 bg-slate-700 mx-1"></div>

                {onCompare && (
                  <button 
                    onClick={onCompare}
                    className="text-slate-400 hover:text-violet-300 transition-colors"
                    title="Compare across mandates"
                  >
                    <Link2 className="w-4 h-4" />
                  </button>
                )}

                <button 
                    onClick={handleEmailExport}
                    className="text-slate-400 hover:text-white transition-colors"
                    title="Export Analysis via Email"
                >
                    <Mail className="w-4 h-4" />
                </button>
            </div>
        </div>
        <p className="text-slate-400 text-sm mb-6">{evaluation.oneLineSummary}</p>
        
        {mandateName && (
          <div className="mb-4 inline-flex items-center gap-2 px-3 py-1 bg-violet-900/20 border border-violet-500/30 rounded-full text-xs text-violet-300">
            <span className="font-medium">Profile:</span>
            <span>{mandateName}</span>
          </div>
        )}
        
          {evaluation.redFlags.length > 0 && (
            <div className="mb-6 bg-rose-950/30 p-4 border border-rose-900/30 rounded-lg">
              <div className="flex items-center gap-2 text-rose-400 font-semibold text-sm mb-3">
                <AlertTriangle className="w-4 h-4" />
                Red Flags Detected
              </div>
              <ul className="list-disc list-inside text-rose-300/80 text-xs space-y-1">
                {evaluation.redFlags.map((flag, idx) => (
                  <li key={idx}>{flag}</li>
                ))}
              </ul>
            </div>
          )}
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
                 <ScoreRow label="Desirability" score={evaluation.desirability.score} reasoning={evaluation.desirability.reasoning} icon={Heart} />
                 <ScoreRow label="Viability" score={evaluation.viability.score} reasoning={evaluation.viability.reasoning} icon={TrendingUp} />
                 <ScoreRow label="Feasibility" score={evaluation.feasibility.score} reasoning={evaluation.feasibility.reasoning} icon={Cpu} />
            </div>
            <div className="flex items-center justify-center bg-slate-900/50 rounded-lg p-2">
                <CriteriaChart evaluation={evaluation} />
            </div>
        </div>
      </div>

        {/* Sources Section */}
        {evaluation.sources && evaluation.sources.length > 0 && (
          <div className="px-6 py-3 border-t border-slate-700 bg-slate-900/30">
              <div className="flex items-center gap-2 text-slate-400 text-xs font-medium mb-2">
                  <Link2 className="w-3 h-3" />
                  <span>Sources</span>
              </div>
              <div className="flex flex-wrap gap-2">
                  {evaluation.sources.map((url, idx) => (
                      <a 
                        key={idx} 
                        href={url} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="flex items-center gap-1 px-2 py-1 rounded bg-slate-800 text-slate-400 hover:text-violet-300 hover:bg-slate-700 text-[10px] transition-colors border border-slate-700"
                      >
                          <span className="truncate max-w-[150px]">{new URL(url).hostname}</span>
                          <ExternalLink className="w-2.5 h-2.5" />
                      </a>
                  ))}
              </div>
          </div>
      )}

      <div className="mt-auto border-t border-slate-700 p-4 bg-slate-900/50">
        {!showRefine ? (
           <button 
             onClick={() => setShowRefine(true)}
             className="w-full py-2 text-sm text-slate-400 hover:text-white border border-slate-700 hover:border-slate-500 rounded-lg transition-colors flex items-center justify-center gap-2"
           >
             <Sparkles className="w-4 h-4" />
             Refine criteria based on this analysis
           </button>
        ) : (
            <div className="animate-in fade-in slide-in-from-top-2 duration-200">
                
                {/* Header */}
                <div className="flex justify-between items-center mb-2">
                    <span className="text-xs font-bold text-violet-400 uppercase tracking-wider">Criteria Refinement Loop</span>
                    <button onClick={handleCancelRefine} className="text-slate-500 hover:text-white"><X className="w-4 h-4"/></button>
                </div>

                {refineStatus === 'idle' && (
                  <>
                    <p className="text-xs text-slate-400 mb-2">Did the AI get it wrong? Describe what needs to change.</p>
                    <div className="flex gap-2">
                        <input 
                            type="text" 
                            value={refineText}
                            onChange={(e) => setRefineText(e.target.value)}
                            placeholder="e.g. 'We actually accept low TRL if patents are strong'"
                            className="flex-1 bg-slate-800 border border-slate-600 rounded px-3 py-2 text-sm text-white focus:outline-none focus:border-violet-500 placeholder-slate-600"
                            onKeyDown={(e) => e.key === 'Enter' && handleRefineSubmit()}
                            autoFocus
                        />
                        <button 
                            onClick={handleRefineSubmit}
                            className="bg-violet-600 text-white px-3 py-2 rounded text-sm hover:bg-violet-500 font-medium whitespace-nowrap"
                        >
                            Analyze
                        </button>
                    </div>
                  </>
                )}

                {refineStatus === 'processing' && (
                   <div className="flex items-center justify-center py-4 text-violet-400 gap-2">
                       <Loader2 className="w-4 h-4 animate-spin" />
                       <span className="text-sm font-medium">Interpreting your feedback...</span>
                   </div>
                )}

                {refineStatus === 'review' && (
                   <div className="bg-violet-900/20 border border-violet-500/30 p-3 rounded-lg">
                       <p className="text-xs text-violet-300 mb-1 flex items-center gap-1">
                          <Sparkles className="w-3 h-3" />
                          I understood this rule:
                       </p>
                       <textarea
                           value={formalizedRule}
                           onChange={(e) => setFormalizedRule(e.target.value)}
                           className="w-full bg-slate-900/50 border border-slate-600 rounded p-2 text-sm text-white focus:border-violet-500 focus:outline-none mb-2 min-h-[60px]"
                       />
                       <div className="flex justify-end gap-2">
                           <button 
                             onClick={() => setRefineStatus('idle')}
                             className="text-xs text-slate-400 hover:text-white px-2 py-1"
                           >
                             Back
                           </button>
                           <button 
                             onClick={handleConfirmRefine}
                             className="flex items-center gap-1 bg-violet-600 hover:bg-violet-500 text-white px-3 py-1.5 rounded text-xs font-medium transition-colors"
                           >
                             <Save className="w-3 h-3" />
                             Confirm & Save Rule
                           </button>
                       </div>
                   </div>
                )}

            </div>
        )}
      </div>
    </div>
  );
};

export default EvaluationCard;